### ISSUE TITLE
To rename or not to rename, that is the question

### ISSUE THREAD

**Issue by haslinger** [pattex/octopod#4]
Hi @pattex !

Thanks for your wonderful project, we are using it in production now for several weeks at https://aua-uff-co.de/ .
I updated almost all of the components after including the gem's content in the actual project.
I will now - because there is some interest in the Viennese podcasting community - extract the functionality in a proper jekyll-plugin with two aims in mind:
- short term: Easy installation
- long term: Getting Github to approve the gem for Github pages to have a free, secure podcast hosting solution available, that's just browser based.

I will always give credits to your name and project Octopod, because most of the code will still be your's but I guess I will rename it to jekyll-podcasting or something like that, because it derivated quite a lot from Octopod and that name is your's. I assume it is in your interest, that I change the name or would you prefer it to be named jekyll-octopod?

**Comment by haslinger** [comment]
After our short conversation on Twitter: 
In compliance with https://twitter.com/pattex/status/731220688204337152 I will name the Jekyll plugin jekyll-octopod, the Theme Gem jekyll-octopod-theme and speak of Project Octopod as the whole thing.
So I can refer to Octopod as the mascot, which is too cute engangled in it's earphone cables.
Furthermore I don't conflict with your repo octopod or your gem octopod-gem in case you want to proceed with any of these.

**Comment by pattex** [comment]
Ha, super late. Like … always…

I agree and am curious about octopods future. Keep me up to date. :-)
